# This is the workflow file that will be used to manage redshift.

name: Redshift-Workflow

on:
  push:
    branches:
      - main
      #- dev
    paths:
      - 'oid/**'
      - 'dwh/**'
      - 'bigdata/**'
      - 'industrializacion/**'

  workflow_dispatch:
  
concurrency:
  group: Redshift-Workflow
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

env:
  AWS_REGION              : ${{ vars.AWS_REGION }}
  AWS_ROLE                : ${{ secrets.AWS_ROLE }}
  INSTANCE_ID             : ${{ vars.INSTANCE_ID }}
  EC2_SSH_KEY             : ${{ secrets.EC2_SSH_KEY }}
  REDSHIFT_DB             : ${{ secrets.REDSHIFT_DB }}
  REDSHIFT_PASSWORD       : ${{ secrets.REDSHIFT_PASSWORD }}
  REDSHIFT_HOST           : ${{ secrets.REDSHIFT_HOST }}
  REDSHIFT_USER           : ${{ secrets.REDSHIFT_USER }}
  REDSHIFT_PORT           : ${{ secrets.REDSHIFT_PORT }}
  WORKGROUP_NAME          : ${{ secrets.WORKGROUP_NAME }}
  BUCKET_NAME             : ${{ vars.BUCKET_NAME }}

jobs:
  manage-redshift:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM
      
      - name: Changed files
        id: changed-create-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            ./oid/**/**/*.env
            ./dwh/**/*.env
            ./bigdata/**/*.env
            ./industrializacion/**/*.env

      - name: Get info data
        id: get-info-data
        if: ${{ steps.changed-create-files.outputs.all_changed_files!= '' }}
        env:
            FILES: ${{ steps.changed-create-files.outputs.all_changed_files }}
        run: |
          mkdir -p redshift-table-process
          for file in ${{ steps.changed-create-files.outputs.all_changed_files }}; do
            cp -r $file redshift-table-process
          done
          ls -la ./redshift-table-process/
  
      - name: Start Instance
        id: start-instance
        run: |
          echo -e "${{env.INSTANCE_ID}}...\n"
          echo "Checking instance state"
          INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids ${{env.INSTANCE_ID}} --query 'Reservations[*].Instances[*].State.Name' --output text --region ${{ env.AWS_REGION }})
          if [ "$INSTANCE_STATE" = "stopped" ]; then
            aws ec2 start-instances --instance-ids ${{env.INSTANCE_ID}} --region ${{ env.AWS_REGION }}
            echo -e "\n----- Start command sended to ${{env.INSTANCE_ID}} -----"
            echo "Waiting for starting instance"
            while INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids ${{env.INSTANCE_ID}} --query 'Reservations[*].Instances[*].State.Name' --output text --region ${{ env.AWS_REGION }}); test "$INSTANCE_STATE" = "pending"; do sleep 2; echo -n '.'; done
          else
            echo -e "\n-----*******************************-----"
            echo -e "-----EC2 Instance is already started-----"
            echo -e "-----         Stop it first         -----"
            echo -e "-----*******************************-----\n"
          fi
          echo -e "GETTING PUBLIC IP..."
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{env.INSTANCE_ID}} --query "Reservations[*].Instances[*].PublicIpAddress" --output text --region ${{ env.AWS_REGION }})
          echo -e "${INSTANCE_STATE}...\n"
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
  
      - name: Setup SSH Key
        id: setup-ssh-key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.PUBLIC_IP }} >> ~/.ssh/known_hosts
      
      - name: Create environments
        id: create-environment
        run: |
          mkdir environment-variable
          cd environment-variable
          ENV_FILE="environment.env"   
          cat <<EOL > $ENV_FILE
          export BUCKET_NAME=${{ vars.BUCKET_NAME }}
          export REDSHIFT_DB=${{ env.REDSHIFT_DB }}
          export REDSHIFT_USER=${{ env.REDSHIFT_USER }}
          export REDSHIFT_PASSWORD=${{ env.REDSHIFT_PASSWORD }}
          export REDSHIFT_HOST=${{ env.REDSHIFT_HOST }}
          export REDSHIFT_PORT=${{ env.REDSHIFT_PORT }}
          export WORKGROUP_NAME=${{ env.WORKGROUP_NAME }}
          EOL

      - name: Compress files
        id: compress-files
        run: zip -r files.zip redshift-table-process environment-variable code-create-tables
  
      - name: Upload Script to EC2
        id: upload-script
        run: scp -i ~/.ssh/id_rsa files.zip ec2-user@${{ env.PUBLIC_IP }}:/home/ec2-user/
        continue-on-error: false

      - name: Validate script on EC2
        id: validate-script
        run: | 
          ssh -i ~/.ssh/id_rsa ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
          if [[ -e /home/ec2-user/files.zip ]]; 
          then 
            echo -e "SCRIPT EXISTS" 
          else 
            exit 1
          fi
          EOF
        continue-on-error: false
      
      - name: Decompress and Execute Script
        id: descomprimir-y-ejecutar-script
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
          unzip files.zip
          source environment-variable/environment.env
          python3 /home/ec2-user/code-create-tables/code-create-tables.py
          EOF
        continue-on-error: false
      
      - name: Delete files on EC2
        id: delete-files
        run: ssh -i ~/.ssh/id_rsa ec2-user@${{ env.PUBLIC_IP }} 'sudo rm -fr *'
        continue-on-error: false
      
      - name: Stop Instance
        id: stop-instance
        run: |
          echo -e "${{env.INSTANCE_ID}}...\n"
          aws ec2 stop-instances --instance-ids ${{env.INSTANCE_ID}} --region ${{ env.AWS_REGION}}

          echo -e "\n----- Stop command sended to ${{env.INSTANCE_ID}} -----"
          
          echo "Waiting for stopping instance"
          while INSTANCE_STATE_STOP=$(aws ec2 describe-instances --instance-ids ${{env.INSTANCE_ID}} --query 'Reservations[*].Instances[*].State.Name' --output text --region ${{env.AWS_REGION}}); test "${INSTANCE_STATE_STOP}" = "running"; do sleep 2; echo -n '.'; done
          echo -e "${INSTANCE_STATE_STOP}...\n"

          counter_var=0
          while INSTANCE_STATE_STOP=$(aws ec2 describe-instances --instance-ids ${{env.INSTANCE_ID}} --query 'Reservations[*].Instances[*].State.Name' --output text --region ${{env.AWS_REGION}}); test "${INSTANCE_STATE_STOP}" = "stopping"; do 
            sleep 2
            echo -n '.'
            ((counter_var=counter_var+1)) 
            if [ "$counter_var" -gt 10 ]; then
              echo -e "\n-----******************************-----"
              echo -e "-----EC2 Instance is NOT responding-----"
              echo -e "-----        Breaking cycle        -----"
              echo -e "-----******************************-----\n"
              break
            fi
          done
          echo -e "${INSTANCE_STATE_STOP}...\n"
